version: '3.8'

services:
    api:
        container_name: api
        build: .
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - database

    database:
        container_name: database
        image: postgres:16.2
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env
        ports:
            - "5432:5432"

volumes:
    postgres_data:
